### ISSUE TITLE
research updating to 0.11 of react-leaflet and whether it fixes the issues we encountered

### ISSUE THREAD

**Issue by jeffshaver** [jeffshaver/safe-framework#30]

**Comment by jeffshaver** [comment]
issues like the layer group (little popover thing that hides/unhides layers not working)

if it does fix those issues, than create a work ticket, reference it in a comment on this ticket and work on implementation.

**Comment by jpkeyw** [comment]
@jeffshaver is there a particular place that this is being used in the example that I can see what's going on with it? Or somewhere in the code it's being attempted but commented out because it was failing?

**Comment by jeffshaver** [comment]
@jpkeyw @knorris may know a little more since she implemented the Map component in safe-framework

**Comment by jpkeyw** [comment]
Ok, I can't guarantee that upgrading to v0.11 is going to fix the problem. However, it appears that, if it was implemented at all correctly in version before 0.11, the implementation of and syntax for LayersControl for the new version is completely changed. In fact, I can't find anywhere in the older version's code base that points to the syntax currently being used in our code. Version 0.11 has an [example](https://github.com/PaulLeCam/react-leaflet/tree/f7037b9625c7b8ebb001d2c8f5ff7de9fa20934e#layerscontrol) of using LayersControl with the new syntax.

I think it would be worth attempting to modify our code to use the new version. See #32.
