### ISSUE TITLE
Update react-leaflet to v0.11

### ISSUE THREAD

**Issue by jpkeyw** [jeffshaver/safe-framework#32]
Modify our Map code to use LayersControl with the new syntax.

**Comment by knorris** [comment]
The map on SAfE 1.xxxx was changed so that scrolling the map left or right kept the data points on the map. It required this setting in Leaflet:   worldCopyJump: true

Please make the same change for 2.0.

**Comment by jpkeyw** [comment]
Okay, it seems there's a bug in the react-leaflet library. I've filed an issue in that project: PaulLeCam/react-leaflet#145.

**Comment by jeffshaver** [comment]
the react-leaflet ticket was fixed and I updated the branch. it now works. However, it seems like we are going to need some changes regarding the mapping. we are going to need multiple toggleable layers of markers.
